### ISSUE TITLE
Information about the log verbosity can be lost

### ISSUE THREAD

**Issue by 44past4** [go-logr/logr#10] opened 2019-10-07 09:41 UTC
When using V-levels with glog or klog one common pattern is to avoid evaluation of logger invocation arguments when those might not be needed. So instead:
```
log.V(5).Info("Some message", "key", someComplexComputation())
```
something like this is used:
```
if log.V(5) {
  log.Info("Some message", "key", someComplexComputation())
}
```
In logr this translates to:
```
if log.V(5).Enabled() {
  log.Info("Some message", "key", someComplexComputation())
}
```
This unfortunately leads to a situation that the information about the log verbosity might be lost for the underlying logger implementation.
This can be problematic for implementations which have a fixed list of logging levels containing more then just error and info and would like to map different v-levels to the underlying logging levels.

This can be fixed by repeating V() function invocation:
```
if log.V(5).Enabled() {
  log.V(5).Info("Some message", "key", someComplexComputation())
}
```
but as this is not enforced by the API this might be error prone.

Some alternatives worth considering:

- Do not embed logr.InfoLogger in logr.Logger. This way following code will not compile:
```
if log.V(5).Enabled() {
  log.Info("Some message", "key", someComplexComputation())
}
```

- Remove V() method and logr.InfoLogger interface completely and pass verbosity as argument to Info method:

```
if log.InfoEnabled(5) {
  log.Info(5, "Some message", "key", someComplexComputation())
}
```

- Use closure with Enabled():
 ```
log.V(5).IfEnabled(func(log logr.InfoLogger) {
  log.Info("Some message", "key", someComplexComputation())
})
```

**Comment by DirectXMan12** [comment] 2019-10-08 01:40
FWIW, you can also use this pattern

```go
if log := log.V(5); log.Enabled() {
  log.Info(...)
}
```

or, you can do what Zap does, and delay the computation till the end, so instead of calling `someExpensiveComputation`, you call `LightweightConstructor`, which returns an object that implements serialization that does the expensive computation.  Such a pattern is supported in Zap currently, but not yet explicitly in logr.  I've been considering it, though.

> Do not embed logr.InfoLogger in logr.Logger. This way following code will not compile:

That's not super-ergonomic for cases that would otherwise turn into `log.V(0).Info` (it's not too bad, but it's not great), which are currently fairly common.  That kinda depends on how common it is to log @ level zero.  Similarly, it won't (currently) prevent the same issue with Error, since that doesn't take V levels.  It doesn't work if we adopt some of the suggestions in #6 (not saying we're going to, but something to consider).

> Remove V() method and logr.InfoLogger interface completely and pass verbosity as argument to Info method

That's not great because it prevents you from passing around an info logger and/or is rendered moot by #6)

> Use closure with Enabled

This one's interesting, but it's a heavier-weight version of the above compound if statement, which doesn't require changing the api and is significantly less typing.

**Comment by 44past4** [comment] 2019-10-08 07:02
Delaying the evaluation of arguments by wrapping them with a lazy evaluated function will work for many cases but not all. In Kubernetes code base there is at least a few places where following pattern is used:

```
if log.V(5) {
  for _, elem := range someCollection {
    log.Info("Some message", "elem", elem)
 }
}
```

> That's not super-ergonomic for cases that would otherwise turn into log.V(0).Info (it's not too bad, but it's not great), which are currently fairly common. 

In current master branch of Kubernetes repository there is (I used a simple grep over all *.go files so this might not be 100% accurate):
- klog.V(*) - 6807 matches
- klog.Info* - 905 matches
- klog.Warning* - 763 matches
- klog.Error* - 2120 matches
- klog.Fatal* - 320 matches

So assuming that all klog.Info* will turn into logr.V(1).Info() or  logr.V(2).Info() and all klog.Warn* will turn into logr.V(0).Info() it will be less than 10% of cases where logr.V(0) would be used.
Depending on your opinion this may or may not be worth optimization.

**Comment by DirectXMan12** [comment] 2019-10-08 20:30
hmm... those numbers aren't terrible k8s wise.  Might be annoying for other users (would probably be a version bump).  Depending on #6, this is still potentially problematic, but it would solve the problem at the moment.

Don't mean to be negative here, just trying to figure out the tradeoffs.

Ignoring vendor (but including staging), we've go 29 instances of `if klog.V` (`~[go:kubernetes] $ ag --ignore-dir=vendor 'if klog.V' | wc -l`).  That's not a ton.  A quick survey suggests that a few of those wouldn't survive the conversion anyway.

**Comment by DirectXMan12** [comment] 2019-10-08 20:31
(P.S. warning is a bit odd here -- I was under the impression that we weren't supposed to use it in k8s anyway, but we seem to have a decent number of instances.  If we didn't have warning, than we'd be in the same situation as we are with klog)

**Comment by thockin** [comment] 2020-05-28 05:22
I think call-sites that do

```
if log.V(5).Enabled() {
    log.Info(...)
}
```

...are broken and should be fixed.  I like @DirectXMan12 idea of compound `if` best of all the ideas, and as to #6, I think we should get rid of InfoLogger, so those options are out, anyway.

Closing as "working as intended" :)  Convince me otherwsie and reopen.

**Closed by thockin** 2020-05-28 05:22 UTC
